# System settings
system:
  # Server listening
  bind:
    # Server listening port.
    # REQUIRED
    #port: 25500
  request:
    header_readlimit: 65536
    default_protocol: "HTTP/0.9"
    header_limit: 127
    default_content_type: "application/json"

  route_paths:
    - src/server/handler_root/
